config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'drinks#index'

  resources :drinks

  resources :drink_types

  resources :services

  resources :drinkwares

  resources :ingredient_types

  resources :ingredients

  resources :brands

  resources :quantities

  resources :units
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :ingredient

  validates :name, presence: true
  validates :description, presence: true
  validates :in_stock, inclusion: [true, false]
  validates :ingredient_id, presence: true, uniqueness: { scope: :name, message: 'This Brand already exists for this Ingredient' }
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :service
  belongs_to :drinkware
  belongs_to :drink_type
  has_many :drink_ingredients

  validates :name, presence: true
  validates :drink_type_id, presence: true
  validates :description, presence: true
  validates :preparation, presence: true
  validates :service_id, presence: true
  validates :drinkware_id, presence: true

  def can_be_made?
    drink_ingredients = self.drink_ingredients

    # ingredients can be in_stock or have a brand with in_stock
    in_stocks = drink_ingredients.map do |drink_ingredient|
      drink_ingredient.ingredient.in_stock || drink_ingredient.ingredient.brands.pluck(:in_stock).any?
    end

    in_stocks.all?
  end
end

app/models/drink_category.rb
class DrinkCategory < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/drink_ingredient.rb
class DrinkIngredient < ApplicationRecord
  belongs_to :drink
  belongs_to :ingredient
  belongs_to :quantity
  belongs_to :unit

  validates :drink_id, presence: true
  validates :ingredient_id, presence: true
  validates :quantity_id, presence: true
  validates :unit_id, presence: true
end

app/models/drink_type.rb
class DrinkType < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/drinkware.rb
class Drinkware < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :ingredient_type
  has_many :brands
  has_many :drink_ingredients

  validates :name, presence: true
  validates :ingredient_type_id, presence: true
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
  has_many :ingredients

  validates :name, presence: true
end

app/models/ingredient_type.rb
class IngredientType < ApplicationRecord
  has_many :ingredients

  validates :name, presence: true
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  has_many :drink_ingredients

  validates :amount, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :drink_ingredients

  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(drink_params)
      redirect_to @brand
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    redirect_to brands_path, status: :see_other
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :description, :in_stock, :ingredient_type_id, :ingredient_id)
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @search = ransack_params
    @search.sorts = 'name asc' if @search.sorts.empty?
    @drinks = @search.result.page(params[:page])
  end

  def show
    @drink = Drink.find(params[:id])
  end

  def new
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(drink_params)

    if @drink.save
      redirect_to @drink
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @drink = Drink.find(params[:id])
  end

  def update
    @drink = Drink.find(params[:id])

    if @drink.update(drink_params)
      redirect_to @drink
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy

    redirect_to drinks_path, status: :see_other
  end

  private

  def drink_params
    params.require(:drink).permit(:name, :description, :preparation, :service_id, :drinkware_id, :drink_category_id)
  end

  def ransack_params
    Drink.ransack(params[:q])
  end

  def ransack_result
    @search.result(distinct: true)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to @service
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_path, status: :see_other
  end

  private

  def service_params
    params.require(:service).permit(:name)
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to @unit
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to units_path, status: :see_other
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :abbreviation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    request.path == path ? 'active' : ''
  end

  def active_link_to(name, path)
    link_to(name, path, class: "nav-link #{active_class(path)}")
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
  def display_results_header(count)
    "#{pluralize(count, 'Drink')} match#{count == 1 ? 'es' : ''}"
  end
end

app/helpers/drinkware_helper.rb
module DrinkwareHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/drinks/_form.html.erb
<%= form_with model: @drink do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @drink.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :drink_type_id %><br>
    <%= form.collection_select :drink_type_id, DrinkType.all, :id, :name, include_blank: true %>
    <% @drink.errors.full_messages_for(:drink_type_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @drink.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :preparation %><br>
    <%= form.text_area :preparation %>
    <% @drink.errors.full_messages_for(:preparation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :service_id %><br>
    <%= form.collection_select :service_id, Service.all, :id, :name, include_blank: true %>
    <% @drink.errors.full_messages_for(:service_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :drinkware_id %><br>
    <%= form.collection_select :drinkware_id, Drinkware.all, :id, :name, include_blank: true %>
    <% @drink.errors.full_messages_for(:drinkware_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Drinks#edit</h1>

<%= render 'form', drink: @drink %>

app/views/drinks/index.html.erb
<div class="container">
  <h2>Search</h2>

  <div class="mb-3">
    <%= search_form_for @search, :remote=>"true", url: drinks_path, :method => :get do |f| %>
      <div class="mb-1">
        <%= f.label :name_cont %>
        <%= f.search_field :name_cont %>
      </div>

      <div class="mb-1">
        <%= f.label :drink_ingredients_ingredient_id_eq, 'Contains ingredient' %>
        <%= f.collection_select :drink_ingredients_ingredient_id_eq, Ingredient.all, :id, :name, include_blank: true %>
      </div>

      <%= f.submit %>
    <% end %>
  </div>

  <%= tag.h2 display_results_header(@drinks.total_count) %>

  <table class="table table-striped table-hover table-borderless table-sm">
    <thead>
      <tr>
        <th>
          <%= sort_link @search, :name, 'Name', { :remote => true, :method => :get } %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @drinks.each do |drink| %>
        <tr>
          <td>
            <%= link_to drink.name, drink %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @drinks, :theme => 'bootstrap-5'%>

  <h2>Add</h2>

  <p><%= link_to 'New Drink', new_drink_path %></p>
</div>

app/views/drinks/new.html.erb
<h1>Drinks#new</h1>

<%= render 'form', drink: @drink %>

app/views/drinks/show.html.erb
<h1><%= @drink.name %>
  <span class="small"><%= link_to 'Edit', edit_drink_path(@drink) %></span>
  <span class="small"><%= link_to 'Destroy', drink_path(@drink), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></span>
</h1>

<div class="section"><%= @drink.description %></div>

<div class="section">
  <div>Type: <%= @drink.drink_type.name %></div>
  <div>Served: <%= @drink.service.name %></div>
  <div>Standard drinkware: <%= @drink.drinkware.name %></div>
</div>

<div class="section">
  <div>Ingredients:</div>
  <ul>
    <% @drink.drink_ingredients.each do |drink_ingredient| %>
      <li>
        <%= number_to_human(drink_ingredient.quantity.amount) %> <%= drink_ingredient.unit.abbreviation %> <%= drink_ingredient.ingredient.name %>
      </li>
    <% end %>
  </ul>
</div>

<div class="section">Preparation: <%= @drink.preparation %></div>

<div class="section">All ingredients in stock: <%= @drink.can_be_made? %></div>