config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'drinks#index'

  resources :drinks

  resources :drink_types

  resources :services

  resources :drinkwares

  resources :ingredient_types

  resources :ingredients

  resources :brands

  resources :quantities

  resources :units
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :ingredient

  validates :name, presence: true
  validates :description, presence: true
  validates :in_stock, inclusion: [true, false]
  validates :ingredient_id, presence: true, uniqueness: { scope: :name, message: 'This Brand already exists for this Ingredient' }
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :service
  belongs_to :drinkware
  belongs_to :drink_type
  has_many :drink_ingredients

  validates :name, presence: true
  validates :drink_type_id, presence: true
  validates :description, presence: true
  validates :preparation, presence: true
  validates :service_id, presence: true
  validates :drinkware_id, presence: true

  def can_be_made?
    drink_ingredients = self.drink_ingredients

    # ingredients can be in_stock or have a brand with in_stock
    in_stocks = drink_ingredients.map do |drink_ingredient|
      drink_ingredient.ingredient.in_stock || drink_ingredient.ingredient.brands.pluck(:in_stock).any?
    end

    in_stocks.all?
  end
end

app/models/drink_category.rb
class DrinkCategory < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/drink_ingredient.rb
class DrinkIngredient < ApplicationRecord
  belongs_to :drink
  belongs_to :ingredient
  belongs_to :quantity
  belongs_to :unit

  validates :drink_id, presence: true
  validates :ingredient_id, presence: true
  validates :quantity_id, presence: true
  validates :unit_id, presence: true
end

app/models/drink_type.rb
class DrinkType < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/drinkware.rb
class Drinkware < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :ingredient_type
  has_many :brands
  has_many :drink_ingredients

  validates :name, presence: true
  validates :ingredient_type_id, presence: true
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
  has_many :ingredients

  validates :name, presence: true
end

app/models/ingredient_type.rb
class IngredientType < ApplicationRecord
  has_many :ingredients

  validates :name, presence: true
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  has_many :drink_ingredients

  validates :amount, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :drinks

  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :drink_ingredients

  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(drink_params)
      redirect_to @brand
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    redirect_to brands_path, status: :see_other
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :description, :in_stock, :ingredient_type_id, :ingredient_id)
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to @unit
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to units_path, status: :see_other
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :abbreviation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    request.path == path ? 'active' : ''
  end

  def active_link_to(name, path)
    link_to(name, path, class: "nav-link #{active_class(path)}")
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
  def display_results_header(count)
    "#{pluralize(count, 'Drink')} match#{count == 1 ? 'es' : ''}"
  end
end

app/helpers/drinkware_helper.rb
module DrinkwareHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/brands/_form.html.erb
<%= form_with model: @brand do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @brand.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @brand.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :in_stock %><br>
    <%= form.check_box :in_stock %>
    <% @brand.errors.full_messages_for(:in_stock).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :ingredient_id %><br>
    <%= form.collection_select :ingredient_id, Ingredient.all, :id, :name, include_blank: true %>
    <% @brand.errors.full_messages_for(:ingredient_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Brands#edit</h1>

<%= render 'form', brand: @brand %>

app/views/brands/index.html.erb
<h1>Brands#index</h1>

<ul>
  <% @brands.each do |brand| %>
    <li>
      <%= link_to "#{brand.name} #{brand.ingredient.name}", brand %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'New Brand', new_brand_path %></p>

app/views/brands/new.html.erb
<h1>Brands#new</h1>

<%= render 'form', brand: @brand %>

app/views/brands/show.html.erb
<h1>Brands#show</h1>

<h2><%= @brand.name %></h2>
<p><%= @brand.description %></p>
<p><%= @brand.in_stock %></p>
<p><%= @brand.ingredient.name %></p>

<ul>
  <li><%= link_to 'Edit', edit_brand_path(@brand) %></li>
  <li><%= link_to 'Destroy', brand_path(@brand), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
</ul>